### ISSUE TITLE
Clicking the "Print QR Code Button" - Part 5, Displaying the QR Code PDF

### ISSUE THREAD

**Issue by pkriengsiri** [pkriengsiri/whats-in-the-box#16]
**Overarching user story:**
As a disorganized person who's moving
I want a system to track what's in each box
So that I know what's in each box before I open it and scatter the contents

**Issue user story:**
As a disorganized person who's moving
I want a way to label a box
So that I can view the label and know what the contents is

**Acceptance criteria**
Given the QR code PDF has been generated
When I access the PDF
Then it should be displayed on the screen for the user to print.

**Comment by mollymccollumwx** [comment]
Taken care of in issue 15
