### ISSUE TITLE
Create "About Us" page

### ISSUE THREAD

**Issue by mollymccollumwx** [pkriengsiri/whats-in-the-box#45]
Overarching user story:
As a disorganized person who's moving
I want a system to track what's in each box
So that I know what's in each box before I open it and scatter the contents

Issue user story:
As a disorganized person who's moving
I want to know who created the website I am using 
So that I can thank them for keeping me organized 

Acceptance criteria:
Given that has accessed the application
When they click on the link for About Us in the dropdown menu
They are presented with a page that displays information and ways to contact the creators

**Comment by pkriengsiri** [comment]
Create an aboutus folder in the root directory
Create an index.html in the new folder
