### ISSUE TITLE
Open PDF on a new tab in the browser

### ISSUE THREAD

**Issue by mollymccollumwx** [pkriengsiri/whats-in-the-box#47]
Overarching user story:
As a disorganized person who's moving
I want a system to track what's in each box
So that I know what's in each box before I open it and scatter the contents

Issue user story:
As a disorganized person who's moving
I want open the PDF in a different browser
So that I don't have to reopen the main website window

Acceptance criteria:
Given that the user has generated the QR code
When they click on the button to print the QR code
They are presented with PDF in a different tab in the browser

**Comment by pkriengsiri** [comment]
Closed by mugi
