### ISSUE TITLE
add links to about us section

### ISSUE THREAD

**Issue by Marquez-Brown** [pkriengsiri/whats-in-the-box#68]
Overarching user story:
As a disorganized person who's moving
I want a system to track what's in each box
So that I know what's in each box before I open it and scatter the contents

Issue user story:
As a developer working on this app
I want to be able to easily read the code
So that I can understand what each part is doing

Acceptance criteria
Given that the user (developer) views the about us section
The user (developer) can each profile
Then they should see a summary of the user, linked in and git hub links

**Comment by pkriengsiri** [comment]
Marquez finished.
