### ISSUE TITLE
Change text sizes on scan.html

### ISSUE THREAD

**Issue by mollymccollumwx** [pkriengsiri/whats-in-the-box#83]
Overarching user story:
As a disorganized person who's moving
I want a system to track what's in each box
So that I know what's in each box before I open it and scatter the contents

Issue user story:
As a disorganized person who's moving
I want to use a simple, visually-pleasing website
So that I can keep track of my boxes and their contents as I move

Acceptance criteria:
Given that user opens the a page with the box contents
The user is greeted with easily discerned sections
So that the user experience is pleasant

**Comment by pkriengsiri** [comment]
Fixed by Molly
